#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.


# start cache
cd $OPENSHIFT_DATA_DIR/installs/memcached/bin
./memcached -d -s ${OPENSHIFT_TMP_DIR}cache_file.sock
